name: supabase_database_client
description: Supabase database client
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  intl: ^0.17.0
  iot_api:
    path: ../iot_api
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  rxdart: ^0.27.5
  supabase_flutter: ^0.3.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
