name: user_repository
description: A package which manages the user domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  iot_api:
    path: ../iot_api
  iot_gateway:
    path: ../iot_gateway
  mocktail: ^0.3.0
  supabase_auth_client:
    path: ../supabase_auth_client
  supabase_database_client:
    path: ../supabase_database_client
  supabase_flutter: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
