name: flutter_firestore
description: An example firestore app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  bloc: ^8.0.3
  equatable: ^2.0.3
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  http: ^ 0.13.4
  intl: ^0.17.0
  iot_api:
    path: packages/iot_api
  iot_repository:
    path: packages/iot_repository
  remote_storage_iot_api:
    path: packages/remote_storage_iot_api

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
