name: flutter_firestore
description: An example firestore app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_map: ^1.1.1
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^ 0.13.4
  intl: ^0.17.0
  iot_api:
    path: packages/iot_api
  iot_repository:
    path: packages/iot_repository
  latlong2: ^0.8.1
  remote_storage_iot_api:
    path: packages/remote_storage_iot_api
  iot_gateway:
    path: packages/iot_gateway
  json_annotation: ^4.6.0
  json_path: ^0.4.1
  url_launcher: ^6.1.5

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icon/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
