name: iot_api
description: The interface and models for an API providing access to IoT.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.3.1
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
