name: iot_gateway
description: An iot gateway that interacts with adafruit-io using mqqt
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

dependencies: 
  iot_api:
    path: ../iot_api
  mqtt5_client: ^3.3.0
  mqtt_client: 9.6.8
  rxdart: ^0.27.5
  uuid: ^3.0.6
